/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tp.pp2.rpg.generator.core;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
